### ISSUE TITLE
Invalid syntax when run on ubuntu

### ISSUE THREAD

**Issue by stuin** [veggiedefender/tty-countdown#1]
File "/usr/bin/tty-countdown", line 94
    print(center(asciiFormat(t, font), getTermDimansions(), end="")
                                                                                                  ^
SyntaxError: invalid syntax

**Comment by stuin** [comment]
arrow pointing at = sign

**Comment by veggiedefender** [comment]
Check `python -V`. This is a python 3 script and iirc Ubuntu uses python 2 by default. If you open up /usr/bin/tty-countdown and change the line at the top so it says `python3` instead of `python` then it'll probably work.

**Comment by stuin** [comment]
Thanks that did it.
