### ISSUE TITLE
Installing from AUR causes stat error

### ISSUE THREAD

**Issue by ghost** [veggiedefender/tty-countdown#3]
If i `yay -S tty-countdown-git` or i git clone it and `makepkg -si` it will fail with the error

```bash
cp: cannot stat 'tty-countdown': no such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: tty-countdown-git
```

**Comment by veggiedefender** [comment]
I'm a bit busy this week so you can either wait a bit or submit a PR if you're up for the task.

The problem likely comes from a recent commit which renamed `tty-countdown` to `tty-countdown.py` and the pkgbuild on the AUR is still expecting `tty-countdown` without the extension.

A quick fix would be to just rename the file back to `tty-countdown`.

The longer term fix might be to keep the current file naming, and have `tty-countdown` be a shell script which runs `tty-countdown.py` using the appropriate python version/executable.

**Comment by kndwin** [comment]
I was brainstorming on the longer term fix and had 3 approaches that could work.

1. Revert the naming convention (Easiest)
I reviewed the commit that made the change and understand that it was for syntax correctness. Just wondering if it's worthwhile to revert it if it's breaking the AUR build process.
```
Commit: 3308877e4c61e0edb0adaa69cc3e6c31f7ea18e9
Title: rename script with proper Python ending
Description: Python scripts should have the ending '.py'
```
2. Duplicate "tty-countdown.py" file and drop the ".py" extension (Also easy but not DRY)
3. Modify the AUR package to move "tty-countdown.py" to /usr/share and create a bash script "tty-countdown" that runs the python script. (Harder but most complete)

If you're okay with approach 3, I can email you the git-ready patch for the PKGBUILD and submit a PR here for the "tty-countdown" bash script.

**Comment by veggiedefender** [comment]
hey @kndwin thanks for reminding me that this project exists haha

I ended up just adding a little shell script in the AUR package, since I think this repo shouldn't have any opinions on where it is installed to.

Let me know if it still doesn't work for you, or if I violated any AUR best practices by doing it this way: https://aur.archlinux.org/cgit/aur.git/tree/?h=tty-countdown-git
